=== Kjawo/xml-zadanie-1/xml-zadanie-1/xml-zadanie-1.dtd
<!ELEMENT bookStore (description|authors|genres|coverTypes|publishers|books)*>
<!ELEMENT description (header)*>
<!ELEMENT header (mainTitle|hDescription|hStudents)*>
<!ELEMENT mainTitle (#PCDATA)>
<!ELEMENT hDescription (#PCDATA)>
<!ELEMENT hStudents (student)*>
<!ELEMENT student (firstName|lastName|indexNr)*>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT indexNr (#PCDATA)>
<!ELEMENT authors (author)*>
<!ELEMENT author (firstName|lastName|birthDate)*>
<!ATTLIST author
        authorID ID #REQUIRED>
<!ELEMENT birthDate (#PCDATA)>
<!ELEMENT genres (genre)*>
<!ELEMENT genre (#PCDATA)>
<!ATTLIST genre
        genreID ID #REQUIRED>
<!ELEMENT coverTypes (coverType)*>
<!ELEMENT coverType (#PCDATA)>
<!ATTLIST coverType
        coverTypeID ID #REQUIRED>
<!ELEMENT publishers (publisher)*>
<!ELEMENT publisher (#PCDATA)>
<!ATTLIST publisher
        publisherID ID #REQUIRED>
<!ELEMENT books (book)*>
<!ELEMENT book (title|pages|publishYear|price|frontCover|isbn)*>
<!ATTLIST book
        authorID IDREF #REQUIRED
        coverTypeID IDREF #REQUIRED
        genreID IDREF #REQUIRED
        publisherID IDREF #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT pages (#PCDATA)>
<!ELEMENT publishYear (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT frontCover (#PCDATA)>
<!ATTLIST frontCover
        src CDATA #IMPLIED>
<!ELEMENT isbn (#PCDATA)>

=== Kjawo/xml-zadanie-1/xml-zadanie-1/xml-zadanie-1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<?xml-stylesheet type="text/css" href="xml-zadanie-1.css"?>
<!DOCTYPE bookStore SYSTEM "xml-zadanie-1.dtd">

<bookStore>
	<description>
		<header>
			<hMainTitle>INWENTARZ KSIĄŻEK</hMainTitle>
			<hDescription>Technologie XML - FTIMS 2018/19</hDescription>
			<hStudents>
				<student>
					<firstName>Konrad</firstName>
					<lastName>Jaworski</lastName>
					<indexNr>216782</indexNr>
				</student>
				<student>
					<firstName>Tomasz</firstName>
					<lastName>Witczak</lastName>
					<indexNr>216782</indexNr>
				</student>
			</hStudents>
		</header>
	</description>
	<authors>
		<author authorID="ASapko">
			<firstName>Andrzej</firstName>
			<lastName>Sapkowski</lastName>
			<birthDate>21-06-1948</birthDate>
		</author>
		<author authorID="SKing">
			<firstName>Stephen</firstName>
			<lastName>King</lastName>
			<birthDate>21-09-1947</birthDate>
		</author>
		<author authorID="UEco">
			<firstName>Umberto</firstName>
			<lastName>Eco</lastName>
			<birthDate>05-01-1932</birthDate>
		</author>
		<author authorID="BPrus">
			<firstName>Bolesław</firstName>
			<lastName>Prus</lastName>
			<birthDate>20-08-1847</birthDate>
		</author>
	</authors>
	
	<genres>
		<genre genreID="fantasy">fantasy</genre>
		<genre genreID="horror">horror</genre>
		<genre genreID="crime">crime</genre>
		<genre genreID="social novel">social novel</genre>
	</genres>
	
	<coverTypes>
		<coverType coverTypeID="paperback">paperback</coverType>
		<coverType coverTypeID="hardback">hardback</coverType>
	</coverTypes>
	
	<publishers>
		<publisher publisherID="superNOWA">superNOWA</publisher>
		<publisher publisherID="Viking">Viking</publisher>
		<publisher publisherID="Doubleday">Doubleday</publisher>
		<publisher publisherID="Signet Books">Signet Books</publisher>
		<publisher publisherID="Bompiani">Bompiani</publisher>
		<publisher publisherID="Gebethner i Wolff">Gebethner i Wolff</publisher>
	</publishers>
	
	<books>
		<book authorID="ASapko" genreID="fantasy"
				coverTypeID="paperback" publisherID="superNOWA">
			<frontCover src="OstatnieZyczenie.jpg" />
			<title>Ostatnie Życzenie</title>
			<!--<pustyGrid />-->
			<pages>288</pages>
			<publishYear>1993</publishYear>
			<price>35,99</price>
			<isbn>978-0-575-08244-1</isbn>
			<!--<author1> Andrzej Sapkowski </author1>-->
		</book>
		<book authorID="ASapko" genreID="fantasy"
				coverTypeID="paperback" publisherID="superNOWA">
			<frontCover src="MieczPrzeznaczenia.jpg" />
			<title>Miecz przeznaczenia</title>
			<pages>384</pages>
			<publishYear>1992</publishYear>
			<price>35,99</price>
			<isbn>978-1-4732-1153-7</isbn>
		</book>
		<book authorID="ASapko" genreID="fantasy"
				coverTypeID="paperback" publisherID="superNOWA">
			<frontCover src="KrewElfow.jpg" />
			<title>Krew elfów</title>
			<pages>320</pages>
			<publishYear>1994</publishYear>
			<price>35,99</price>
			<isbn>978-0-575-08484-1</isbn>
		</book>
		<book authorID="ASapko" genreID="fantasy"
				coverTypeID="paperback" publisherID="superNOWA">
			<frontCover src="CzasPogardy.jpg" />
			<title>Czas pogardy</title>
			<pages>352</pages>
			<publishYear>1995</publishYear>
			<price>35,99</price>
			<isbn>978-0-575-09094-1</isbn>
		</book>
		<book authorID="ASapko" genreID="fantasy"
				coverTypeID="paperback" publisherID="superNOWA">
			<frontCover src="ChrzestOgnia.jpg" />
			<title>Chrzest ognia</title>
			<pages>352</pages>
			<publishYear>1996</publishYear>
			<price>35,99</price>
			<isbn>978-0-575-09097-2</isbn>
		</book>
		<book authorID="ASapko" genreID="fantasy"
				coverTypeID="paperback" publisherID="superNOWA">
			<frontCover src="WiezaJaskolki.jpg" />
			<title>Wieża Jaskółki</title>
			<pages>462</pages>
			<publishYear>1997</publishYear>
			<price>35,99</price>
			<isbn>978-0-575-09083-3</isbn>
		</book>
		<book authorID="ASapko" genreID="fantasy"
				coverTypeID="paperback" publisherID="superNOWA">
			<frontCover src="PaniJeziora.jpg" />
			<title>Pani Jeziora</title>
			<pages>544</pages>
			<publishYear>1999</publishYear>
			<price>38,99</price>
			<isbn>978-0-575-09084-4</isbn>
		</book>
		<book authorID="SKing" genreID="horror"
				coverTypeID="paperback" publisherID="Viking">
			<frontCover src="It.jpg" />
			<title>It</title>
			<pages>1376</pages>
			<publishYear>1986</publishYear>
			<price>45,49</price>
			<isbn>0-670-81302-8</isbn>
		</book>
		<book authorID="SKing" genreID="horror"
				coverTypeID="paperback" publisherID="Doubleday">
			<frontCover src="TheShinning.jpg" />
			<title>The Shining</title>
			<pages>447</pages>
			<publishYear>1977</publishYear>
			<price>30,49</price>
			<isbn>978-0-385-12167-5</isbn>
		</book>
		<book authorID="SKing" genreID="fantasy"
				coverTypeID="hardback" publisherID="Signet Books">
			<frontCover src="TheGreenMile.jpg" />
			<title>The Green Mile</title>
			<pages>416</pages>
			<publishYear>1996</publishYear>
			<price>41,49</price>
			<isbn>978-0743210898</isbn>
		</book>
		<book authorID="UEco" genreID="crime"
				coverTypeID="hardback" publisherID="Bompiani">
			<frontCover src="TheNameoftheRose.jpg" />
			<title>The Name of the Rose</title>
			<pages>512</pages>
			<publishYear>1980</publishYear>
			<price>49,99</price>
			<isbn>0-15-144647-4</isbn>
		</book>
		<book authorID="BPrus" genreID="social novel"
				coverTypeID="paperback" publisherID="Gebethner i Wolff">
			<frontCover src="Lalka.jpg" />
			<title>Lalka</title>
			<pages>664</pages>
			<publishYear>1890</publishYear>
			<price>23,23</price>
			<isbn>83-01-05734-3</isbn>
		</book>
	</books>
</bookStore>
